### ISSUE TITLE
onItemclick raise index out of bound exception

### ISSUE THREAD

**Issue by saeed-rz** [orhanobut/dialogplus#102]
hi
i set custom adapter to dialog and set onItemclickListener , but when click on list item app crash and raise index out of bound exception

DialogPlus dialog = DialogPlus.newDialog(this)
                .setAdapter(adapter)
                .setOnItemClickListener(new OnItemClickListener() {
                    @Override
                    public void onItemClick(DialogPlus dialog, Object item, View view, int position)
                    {
                    }
                })
                .setExpanded(true)  // This will enable the expand feature, (similar to android L share dialog)
                .setGravity(Gravity.CENTER)
                .setCancelable(true)
                .create();
        dialog.show();

log cat : 
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:337)
            at android.widget.AdapterView.getItemAtPosition(AdapterView.java:773)
            at com.orhanobut.dialogplus.ListHolder.onItemClick(ListHolder.java:87)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
            at android.widget.AbsListView$3.run(AbsListView.java:3866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5329)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by orhanobut** [comment]
Could you show your adapter implementation as well? Would be great help to reproduce the issue

**Comment by saeed-rz** [comment]
yes, this my adapter
`
public class ForwardListAdapter extends ArrayAdapter<CContact>
{

    private List<CContact> m_Contacts;
    private LayoutInflater inflater;

    public ForwardListAdapter(Context context, List<CContact> contacts)
    {
        super(context, R.layout.row_contact_list);
        m_Contacts = contacts;
        inflater = LayoutInflater.from(context);
    }

    @Override
    public int getCount()
    {
        return m_Contacts.size();
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent)
    {
        View view;
        if (convertView == null) {
            view = inflater.inflate(R.layout.row_contact_list, null);
            // Do some initialization
        } else {
            view = convertView;
        }

        .... some code to set value
        return view;
    }
}
`

**Comment by saeed-rz** [comment]
i found the problem
should override getItem method in custom Adapter

@Override
    public CContact getItem(int position)
    {
        return m_Contacts.get(position);
    }
