### ISSUE TITLE
Didn't restore after screen is rotated. 

### ISSUE THREAD

**Issue by talenguyen** [orhanobut/dialogplus#29]
It's would be better if this work like DialogFragment.

**Comment by ldwonday** [comment]
The demo will be cashed when the dialog dismissed,and the logcat print the error:java.lang.NullPointerException
at android.view.View.drawAnimation(View.java:13968).......
at android.os.Looper.loop(Looper.java:136)...

I don't know why, I can't,location the error.

**Comment by MrOutis** [comment]
I think you need to do this programmatically, something like:
```java
 // NOTE: I'm not sure if this is a bad practice...

static boolean isDialogShowing = false;       

onStart() {
    super.onStart();
    if ( isDialogShowing ) {
        showDialog();
    }
}

showDialog() {
    isDialogShowing = true;

    // Build your dialog here...

    // Whenever you dismiss your dialog, remember to set isDialogShowing to false
}
```

**Comment by Kisty** [comment]
This would be great! If we can build on top of AlertDialog or Dialog, we could use DialogFragment. Not sure how the animations could still work though.

**Comment by Kisty** [comment]
I've got an idea to make this restorable on restore by building on top of Dialog. This would mean we can use a DialogFragment which would restore the dialog. I'll try an experiment and see if the animations, etc. work still. 

What do you think?
