### ISSUE TITLE
The demo will be cashed!!!!

### ISSUE THREAD

**Issue by ldwonday** [orhanobut/dialogplus#30]
The demo will be cashed when the dialog dismissed,and the logcat print the error:java.lang.NullPointerException
at android.view.View.drawAnimation(View.java:13968).......
at android.os.Looper.loop(Looper.java:136)...

I don't know why, I can't location the error. The API level is 21 and 4.4

**Comment by ldwonday** [comment]
![Uploading 2MRJUE1SA2VOIHV)_A9}SR7.png . . .]()

**Comment by ldwonday** [comment]
![Uploading 1.png . . .]()

**Comment by ldwonday** [comment]
![Uploading 12.jpg . . .]()

**Comment by ldwonday** [comment]
@Override
            public void onAnimationEnd(Animation animation) {
            	new Handler().post(new Runnable() {
					@Override
					public void run() {
						// TODO Auto-generated method stub
		                decorView.removeView(rootView);
		                isDismissing = false;
					}
				});
            }
I have slove the problem！~
