### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by josluimg** [orhanobut/dialogplus#43]
java.lang.NumberFormatException
    at org.apache.harmony.luni.util.FloatingPointParser.parseFltImpl(Native Method)
    at org.apache.harmony.luni.util.FloatingPointParser.parseFloat(FloatingPointParser.java:321)
    at java.lang.Float.parseFloat(Float.java:323)
    at android.content.res.TypedArray.getFloat(TypedArray.java:304)
    at android.view.animation.ScaleAnimation.<init>(ScaleAnimation.java:54)
    at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:110)
    at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:106)
    at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:83)
    at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:64)
    at com.orhanobut.dialogplus.DialogPlus.onAttached(DialogPlus.java:506)
    at com.orhanobut.dialogplus.DialogPlus.show(DialogPlus.java:202)

trying:

            DialogPlus dialog = new DialogPlus.Builder(getActivity())
                    .setAdapter(new AdapterAssist(getActivity(), adapter.event.status))
                    .setGravity(DialogPlus.Gravity.CENTER)
                    .setContentHolder(new GridHolder(3))
                    .setOnItemClickListener( ...).create();

        dialog.show();

Bug on: 
 Galaxy S2 (GT-I9100)
Android 2.3.3 - 2.3.7

**Comment by josluimg** [comment]
I resolved using:

            if(Build.VERSION.SDK_INT <= 10)
            {
                dialogBuilder.setInAnimation(R.anim.fadein);
                dialogBuilder.setOutAnimation(R.anim.fadeout);
            }

Fadein.xml

    <alpha xmlns:android="http://schemas.android.com/apk/res/android"
    android:interpolator="@android:anim/accelerate_interpolator"
    android:fromAlpha="0.0" 
    android:toAlpha="1.0" 
    android:duration="400" />

Fadeout.xml

    <alpha xmlns:android="http://schemas.android.com/apk/res/android"
    android:interpolator="@android:anim/accelerate_interpolator"
    android:fromAlpha="1.0" 
    android:toAlpha="0.0" 
    android:duration="400" />

Maybe this can help you

**Comment by orhanobut** [comment]
can you try with 1.6 please?
